### ISSUE TITLE
Twitter側からListを削除するとカラムが消せなくなる

### ISSUE THREAD

**Issue by takax3** [Dragon-Egg/sleeping_syar#23]
## 不具合概要
SleepingSyar上でリストを表示カラムに追加したのち、Twitter側にてリストを削除するとSleepingSyar上からカラムを消せなくなる

## 該当ページ
タイムライン表示ページ

## 発生環境
- 環境：Any
- 端末：ASUS_X00ID
- バージョン（アプリのみ）：2.1.5

## 再現手順
1. 何らかの方法でリストを作る
2. SleepingSyar上の設定からリストを表示するように設定する
3. 何らかの方法でリストを削除する
4. 消せなくなる

## 本来の挙動
消えてほしい

## 修正しないとどう困るか
無駄なカラムが消せない

## 原因
SleepingSyarがTwitter側から取得したリストに対してしか表示/非表示を設定できないため？

**Comment by shin19** [comment]
@takax3 応急対応としてリスト編集画面で存在確認を行うようにしました。
最新バージョンでバグが解消されたかどうかご確認いただけますでしょうか。

**Comment by takax3** [comment]
List編集画面を開くとクラッシュした後、再び起動するとリストのカラムが消失しました。

**Comment by shin19** [comment]
バグ調査
```
java.util.ConcurrentModificationException
	at java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1238)
	at java.util.TreeMap$KeyIterator.next(TreeMap.java:1292)
	at org.dragonegg.ofuton.fragment.UsersListFragment$2.onPostExecute(UsersListFragment.java:180)
	at org.dragonegg.ofuton.fragment.UsersListFragment$2.onPostExecute(UsersListFragment.java:153)
	at android.os.AsyncTask.finish(AsyncTask.java:695)
	at android.os.AsyncTask.-wrap1(Unknown Source:0)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:169)
	at android.app.ActivityThread.main(ActivityThread.java:6521)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by shin19** [comment]
繰り返し処理中に元の配列の要素を消してしまったため発生していた
https://www.jpcert.or.jp/java-rules/msc06-j.html

**Comment by takax3** [comment]
All OK. Thanks you!!!!
