### ISSUE TITLE
画像表示中にAuto-rotateで画面が回ると落ちる

### ISSUE THREAD

**Issue by ys3669** [Dragon-Egg/sleeping_syar#5]
```E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.dragonegg.ofuton.debug, PID: 3070
    java.lang.NullPointerException: Attempt to invoke interface method 'void org.dragonegg.ofuton.widget.Rotatable.rotate(float)' on a null object reference
        at org.dragonegg.ofuton.activity.ImagePreviewActivity.onRotateRightClick(ImagePreviewActivity.java:157)
        at org.dragonegg.ofuton.widget.PreviewNavigation.onClick(PreviewNavigation.java:49)
        at android.view.View.performClick(View.java:6597)
        at android.view.View.performClickInternal(View.java:6574)
        at android.view.View.access$3100(View.java:778)
        at android.view.View$PerformClick.run(View.java:25885)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)```

**Comment by ys3669** [comment]
もういっそ回らなくすればよくない

**Comment by ys3669** [comment]
4df7c15a9c712d2e7548a4dab4b6736778d64f4a で修正

**Comment by shin19** [comment]
コミットしてなかった

**Comment by shin19** [comment]
Fixed
